types:
  Product:
    parent: false
    resourceEnabled: true
    attributes:
      filters: 
      - 'product.recipe_filter'
    properties:
###### Start Custom Fields 
      createdAt:
        range: DateTime
        cardinality: (0..1)
        groups:
        - get_product
        - set_product
      recipe:
        range: Recipe
        cardinality: (*..1)
        groups:
        - get_product
        - set_product
###### End Custom Fields 
