<?php

namespace NoInc\SimpleStorefrontBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecipesAndIngredients()
    {
        $recipes = $this->createQueryBuilder('recipe')
        ->addSelect('recipe')
        ->addSelect('recipeIngredients')
        ->addSelect('ingredient')
        ->addSelect('products')
        ->join('recipe.recipeIngredients', 'recipeIngredients')
        ->join('recipeIngredients.ingredient', 'ingredient')
        ->leftJoin('recipe.products', 'products')
        ->getQuery()
        ->getResult();
        
        return $recipes;
    }
}
